/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardImportRouteImport } from './routes/dashboard/import'
import { Route as ApiSeedRouteImport } from './routes/api/seed'
import { Route as ApiHealthcheckRouteImport } from './routes/api/healthcheck'
import { Route as PublicMitmachenRouteImport } from './routes/_public/mitmachen'
import { Route as PublicImpressumRouteImport } from './routes/_public/impressum'
import { Route as PublicDatenschutzRouteImport } from './routes/_public/datenschutz'
import { Route as DashboardInstancesRouteRouteImport } from './routes/dashboard/instances/route'
import { Route as DashboardInstancesIndexRouteImport } from './routes/dashboard/instances/index'
import { Route as PublicViewDataIndexRouteImport } from './routes/_public/view-data/index'
import { Route as ApiOrpcSplatRouteImport } from './routes/api/orpc.$'
import { Route as DashboardInstancesInstanceIdRouteRouteImport } from './routes/dashboard/instances/$instanceId/route'
import { Route as DashboardInstancesInstanceIdIndexRouteImport } from './routes/dashboard/instances/$instanceId/index'
import { Route as PublicViewDataInstanceIdIndexRouteImport } from './routes/_public/view-data/$instanceId/index'
import { Route as DashboardInstancesInstanceIdSessionRouteImport } from './routes/dashboard/instances/$instanceId/session'
import { Route as ApiInstanceInstanceIdSessionsRouteImport } from './routes/api/instance/$instanceId/sessions'
import { Route as PublicViewDataInstanceIdSessionRouteImport } from './routes/_public/view-data/$instanceId/session'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthcheckRoute = ApiHealthcheckRouteImport.update({
  id: '/api/healthcheck',
  path: '/api/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicMitmachenRoute = PublicMitmachenRouteImport.update({
  id: '/mitmachen',
  path: '/mitmachen',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicImpressumRoute = PublicImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicDatenschutzRoute = PublicDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DashboardInstancesRouteRoute = DashboardInstancesRouteRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInstancesIndexRoute = DashboardInstancesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardInstancesRouteRoute,
} as any)
const PublicViewDataIndexRoute = PublicViewDataIndexRouteImport.update({
  id: '/view-data/',
  path: '/view-data/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiOrpcSplatRoute = ApiOrpcSplatRouteImport.update({
  id: '/api/orpc/$',
  path: '/api/orpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInstancesInstanceIdRouteRoute =
  DashboardInstancesInstanceIdRouteRouteImport.update({
    id: '/$instanceId',
    path: '/$instanceId',
    getParentRoute: () => DashboardInstancesRouteRoute,
  } as any)
const DashboardInstancesInstanceIdIndexRoute =
  DashboardInstancesInstanceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardInstancesInstanceIdRouteRoute,
  } as any)
const PublicViewDataInstanceIdIndexRoute =
  PublicViewDataInstanceIdIndexRouteImport.update({
    id: '/view-data/$instanceId/',
    path: '/view-data/$instanceId/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const DashboardInstancesInstanceIdSessionRoute =
  DashboardInstancesInstanceIdSessionRouteImport.update({
    id: '/session',
    path: '/session',
    getParentRoute: () => DashboardInstancesInstanceIdRouteRoute,
  } as any)
const ApiInstanceInstanceIdSessionsRoute =
  ApiInstanceInstanceIdSessionsRouteImport.update({
    id: '/api/instance/$instanceId/sessions',
    path: '/api/instance/$instanceId/sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicViewDataInstanceIdSessionRoute =
  PublicViewDataInstanceIdSessionRouteImport.update({
    id: '/view-data/$instanceId/session',
    path: '/view-data/$instanceId/session',
    getParentRoute: () => PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/instances': typeof DashboardInstancesRouteRouteWithChildren
  '/datenschutz': typeof PublicDatenschutzRoute
  '/impressum': typeof PublicImpressumRoute
  '/mitmachen': typeof PublicMitmachenRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/seed': typeof ApiSeedRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/instances/$instanceId': typeof DashboardInstancesInstanceIdRouteRouteWithChildren
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/view-data': typeof PublicViewDataIndexRoute
  '/dashboard/instances/': typeof DashboardInstancesIndexRoute
  '/view-data/$instanceId/session': typeof PublicViewDataInstanceIdSessionRoute
  '/api/instance/$instanceId/sessions': typeof ApiInstanceInstanceIdSessionsRoute
  '/dashboard/instances/$instanceId/session': typeof DashboardInstancesInstanceIdSessionRoute
  '/view-data/$instanceId': typeof PublicViewDataInstanceIdIndexRoute
  '/dashboard/instances/$instanceId/': typeof DashboardInstancesInstanceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/datenschutz': typeof PublicDatenschutzRoute
  '/impressum': typeof PublicImpressumRoute
  '/mitmachen': typeof PublicMitmachenRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/seed': typeof ApiSeedRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/view-data': typeof PublicViewDataIndexRoute
  '/dashboard/instances': typeof DashboardInstancesIndexRoute
  '/view-data/$instanceId/session': typeof PublicViewDataInstanceIdSessionRoute
  '/api/instance/$instanceId/sessions': typeof ApiInstanceInstanceIdSessionsRoute
  '/dashboard/instances/$instanceId/session': typeof DashboardInstancesInstanceIdSessionRoute
  '/view-data/$instanceId': typeof PublicViewDataInstanceIdIndexRoute
  '/dashboard/instances/$instanceId': typeof DashboardInstancesInstanceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/instances': typeof DashboardInstancesRouteRouteWithChildren
  '/_public/datenschutz': typeof PublicDatenschutzRoute
  '/_public/impressum': typeof PublicImpressumRoute
  '/_public/mitmachen': typeof PublicMitmachenRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/seed': typeof ApiSeedRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/instances/$instanceId': typeof DashboardInstancesInstanceIdRouteRouteWithChildren
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/_public/view-data/': typeof PublicViewDataIndexRoute
  '/dashboard/instances/': typeof DashboardInstancesIndexRoute
  '/_public/view-data/$instanceId/session': typeof PublicViewDataInstanceIdSessionRoute
  '/api/instance/$instanceId/sessions': typeof ApiInstanceInstanceIdSessionsRoute
  '/dashboard/instances/$instanceId/session': typeof DashboardInstancesInstanceIdSessionRoute
  '/_public/view-data/$instanceId/': typeof PublicViewDataInstanceIdIndexRoute
  '/dashboard/instances/$instanceId/': typeof DashboardInstancesInstanceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/instances'
    | '/datenschutz'
    | '/impressum'
    | '/mitmachen'
    | '/api/healthcheck'
    | '/api/seed'
    | '/dashboard/import'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/instances/$instanceId'
    | '/api/orpc/$'
    | '/view-data'
    | '/dashboard/instances/'
    | '/view-data/$instanceId/session'
    | '/api/instance/$instanceId/sessions'
    | '/dashboard/instances/$instanceId/session'
    | '/view-data/$instanceId'
    | '/dashboard/instances/$instanceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/datenschutz'
    | '/impressum'
    | '/mitmachen'
    | '/api/healthcheck'
    | '/api/seed'
    | '/dashboard/import'
    | '/dashboard/users'
    | '/dashboard'
    | '/api/orpc/$'
    | '/view-data'
    | '/dashboard/instances'
    | '/view-data/$instanceId/session'
    | '/api/instance/$instanceId/sessions'
    | '/dashboard/instances/$instanceId/session'
    | '/view-data/$instanceId'
    | '/dashboard/instances/$instanceId'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/dashboard'
    | '/login'
    | '/dashboard/instances'
    | '/_public/datenschutz'
    | '/_public/impressum'
    | '/_public/mitmachen'
    | '/api/healthcheck'
    | '/api/seed'
    | '/dashboard/import'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/instances/$instanceId'
    | '/api/orpc/$'
    | '/_public/view-data/'
    | '/dashboard/instances/'
    | '/_public/view-data/$instanceId/session'
    | '/api/instance/$instanceId/sessions'
    | '/dashboard/instances/$instanceId/session'
    | '/_public/view-data/$instanceId/'
    | '/dashboard/instances/$instanceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthcheckRoute: typeof ApiHealthcheckRoute
  ApiSeedRoute: typeof ApiSeedRoute
  ApiOrpcSplatRoute: typeof ApiOrpcSplatRoute
  ApiInstanceInstanceIdSessionsRoute: typeof ApiInstanceInstanceIdSessionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthcheck': {
      id: '/api/healthcheck'
      path: '/api/healthcheck'
      fullPath: '/api/healthcheck'
      preLoaderRoute: typeof ApiHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/mitmachen': {
      id: '/_public/mitmachen'
      path: '/mitmachen'
      fullPath: '/mitmachen'
      preLoaderRoute: typeof PublicMitmachenRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/impressum': {
      id: '/_public/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof PublicImpressumRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/datenschutz': {
      id: '/_public/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof PublicDatenschutzRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/dashboard/instances': {
      id: '/dashboard/instances'
      path: '/instances'
      fullPath: '/dashboard/instances'
      preLoaderRoute: typeof DashboardInstancesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/instances/': {
      id: '/dashboard/instances/'
      path: '/'
      fullPath: '/dashboard/instances/'
      preLoaderRoute: typeof DashboardInstancesIndexRouteImport
      parentRoute: typeof DashboardInstancesRouteRoute
    }
    '/_public/view-data/': {
      id: '/_public/view-data/'
      path: '/view-data'
      fullPath: '/view-data'
      preLoaderRoute: typeof PublicViewDataIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/orpc/$': {
      id: '/api/orpc/$'
      path: '/api/orpc/$'
      fullPath: '/api/orpc/$'
      preLoaderRoute: typeof ApiOrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/instances/$instanceId': {
      id: '/dashboard/instances/$instanceId'
      path: '/$instanceId'
      fullPath: '/dashboard/instances/$instanceId'
      preLoaderRoute: typeof DashboardInstancesInstanceIdRouteRouteImport
      parentRoute: typeof DashboardInstancesRouteRoute
    }
    '/dashboard/instances/$instanceId/': {
      id: '/dashboard/instances/$instanceId/'
      path: '/'
      fullPath: '/dashboard/instances/$instanceId/'
      preLoaderRoute: typeof DashboardInstancesInstanceIdIndexRouteImport
      parentRoute: typeof DashboardInstancesInstanceIdRouteRoute
    }
    '/_public/view-data/$instanceId/': {
      id: '/_public/view-data/$instanceId/'
      path: '/view-data/$instanceId'
      fullPath: '/view-data/$instanceId'
      preLoaderRoute: typeof PublicViewDataInstanceIdIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/dashboard/instances/$instanceId/session': {
      id: '/dashboard/instances/$instanceId/session'
      path: '/session'
      fullPath: '/dashboard/instances/$instanceId/session'
      preLoaderRoute: typeof DashboardInstancesInstanceIdSessionRouteImport
      parentRoute: typeof DashboardInstancesInstanceIdRouteRoute
    }
    '/api/instance/$instanceId/sessions': {
      id: '/api/instance/$instanceId/sessions'
      path: '/api/instance/$instanceId/sessions'
      fullPath: '/api/instance/$instanceId/sessions'
      preLoaderRoute: typeof ApiInstanceInstanceIdSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/view-data/$instanceId/session': {
      id: '/_public/view-data/$instanceId/session'
      path: '/view-data/$instanceId/session'
      fullPath: '/view-data/$instanceId/session'
      preLoaderRoute: typeof PublicViewDataInstanceIdSessionRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicDatenschutzRoute: typeof PublicDatenschutzRoute
  PublicImpressumRoute: typeof PublicImpressumRoute
  PublicMitmachenRoute: typeof PublicMitmachenRoute
  PublicViewDataIndexRoute: typeof PublicViewDataIndexRoute
  PublicViewDataInstanceIdSessionRoute: typeof PublicViewDataInstanceIdSessionRoute
  PublicViewDataInstanceIdIndexRoute: typeof PublicViewDataInstanceIdIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicDatenschutzRoute: PublicDatenschutzRoute,
  PublicImpressumRoute: PublicImpressumRoute,
  PublicMitmachenRoute: PublicMitmachenRoute,
  PublicViewDataIndexRoute: PublicViewDataIndexRoute,
  PublicViewDataInstanceIdSessionRoute: PublicViewDataInstanceIdSessionRoute,
  PublicViewDataInstanceIdIndexRoute: PublicViewDataInstanceIdIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface DashboardInstancesInstanceIdRouteRouteChildren {
  DashboardInstancesInstanceIdSessionRoute: typeof DashboardInstancesInstanceIdSessionRoute
  DashboardInstancesInstanceIdIndexRoute: typeof DashboardInstancesInstanceIdIndexRoute
}

const DashboardInstancesInstanceIdRouteRouteChildren: DashboardInstancesInstanceIdRouteRouteChildren =
  {
    DashboardInstancesInstanceIdSessionRoute:
      DashboardInstancesInstanceIdSessionRoute,
    DashboardInstancesInstanceIdIndexRoute:
      DashboardInstancesInstanceIdIndexRoute,
  }

const DashboardInstancesInstanceIdRouteRouteWithChildren =
  DashboardInstancesInstanceIdRouteRoute._addFileChildren(
    DashboardInstancesInstanceIdRouteRouteChildren,
  )

interface DashboardInstancesRouteRouteChildren {
  DashboardInstancesInstanceIdRouteRoute: typeof DashboardInstancesInstanceIdRouteRouteWithChildren
  DashboardInstancesIndexRoute: typeof DashboardInstancesIndexRoute
}

const DashboardInstancesRouteRouteChildren: DashboardInstancesRouteRouteChildren =
  {
    DashboardInstancesInstanceIdRouteRoute:
      DashboardInstancesInstanceIdRouteRouteWithChildren,
    DashboardInstancesIndexRoute: DashboardInstancesIndexRoute,
  }

const DashboardInstancesRouteRouteWithChildren =
  DashboardInstancesRouteRoute._addFileChildren(
    DashboardInstancesRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardInstancesRouteRoute: typeof DashboardInstancesRouteRouteWithChildren
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardInstancesRouteRoute: DashboardInstancesRouteRouteWithChildren,
  DashboardImportRoute: DashboardImportRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthcheckRoute: ApiHealthcheckRoute,
  ApiSeedRoute: ApiSeedRoute,
  ApiOrpcSplatRoute: ApiOrpcSplatRoute,
  ApiInstanceInstanceIdSessionsRoute: ApiInstanceInstanceIdSessionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
